k2c:
  badwoman: Singapore
  cn: China
  de: Germany
  emi: United Kingdom
  fr: France
  gb: United Kingdom
  jenny: United Kingdom
  sg: Singapore
  tw: Taiwan
  uk: United Kingdom
  us: United States of America
  vic: United Kingdom
  vv: United Kingdom
  wq: United States of America
  zzx: United States of America
last_update: '2022-02-19 18:36:27'
path_src: /home/si9h/COVID-19/csse_covid_19_data/csse_covid_19_daily_reports
