templates_path:
  /root/dosi/data/meme_templates
fonts_path:
  /root/dosi/data/fonts/
font_name:
  simhei.ttf
  # SourceHanSansCN-Regular.otf
surjection:
  表演一下:
    box:
      [[6, 376, 160, 20], [28, 530, 150, 21]]
    # font_size:
    #   [15, 10]
  hug:
    box:
      [[64, 493, 75, 54]]
    # font_size:
    #   [25]
  wish:
    box:
      [[48, 212, 177, 61]]
    # font_size:
    #   [20]
  huqiuhuqiu:
    box:
      [[40, 42, 100, 64], [63, 293, 275, 60]]
    # font_size:
    #   [25, 25]
  孤儿:
    box:
      [[371, 16, 250, 73], [53, 333, 213, 72]]
  好消息:
    box:
      [[194,256,87,35]]
  如何才能:
    box:
      [[160, 221,75,48], [99,516,115,80]]
  路口:
    box:
      [[230,170,144,139], [504,174,203,140], [316, 674, 339, 109]]
    font_size:
      [25, 25, 25]
    font_color:
      ["w", "w", "w"]
  我无法创造奇迹:
    box:
      [[347,23,146,70]]
    font_size:
      [20]
  伤不了我:
    box:
      [[6,395,274,136]]
  dogge:
    box:
      [[26,288,220,45], [339,48,178,90]]

font_color_mapping:
  b: [0,0,0]
  w: [255,255,255]